name: "🧱 Task"
description: Tarea técnica / operativa
labels: [task]
body:
  - type: textarea
    id: desc
    attributes:
      label: "Descripción"
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: "Checklist"
      value: "- [ ] "
